programa: iBalioakFor.c iBalioakWhile.c
	gcc -o iBalioakFor iBalioakFor.c
	gcc -o iBalioakWhile iBalioakWhile.c

exekutatu: iBalioakFor iBalioakWhile
	./iBalioakFor
	./iBalioakWhile

clean:
	rm -f programa *.o
